# Generated by Django 4.2 on 2024-11-21 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_created_at_alter_car_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
