# Generated by Django 4.2 on 2024-11-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='car',
            new_name='car_id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
